base_url: http://localhost:3000
terrain_url: http://0.0.0.0:65002
listen_port: 3000
legacy_de_url: https://legacy-qa.cyverse.org

logging:
    level: info
    label: sonora server

db:
    host: 0.0.0.0 # use the container ip address
    # host: db  # uncomment for dockerized UI
    port: 5432
    user: de
    password: testpassword
    database: de

sessions:
    secret: "keyboard cat"
    secure_cookie: false
    ttl: 8
    poll_interval_ms: 5000

keycloak:
    server_url: "http://0.0.0.0:11111/auth"
    realm: "CyVerse"
    client_id: local-testing
    client_secret: 10f20be1-a98a-48d1-8915-ba926207a570

intercom:
    app_id: appId
    enabled: true
    company_id: DE-DEV
    company_name: DISCOVERY ENVIRONMENT
    user_profile_url: https://app.intercom.com/apps/appId/users/show?user_id=

admin:
    groups: some-group
    group_attribute_name: entitlement

analysis:
    support:
        user: siuser
        source_id: ldap

irods:
    home_path: /iplant/home
    trash_path: /iplant/trash/home/de-irods
    community_path: /iplant/home/shared
    web_dav:
        anon_uri: https://data.cyverse.org/dav-anon  

fileIdentifier:
    htPathList: "# application/vnd.de.path-list+csv; version=1"
    multiInputPathList: "# application/vnd.de.multi-input-path-list+csv; version=1"

analytics:
    enabled: false
    id: ga-id

vice:
    defaultImage: discoenv/cas-proxy
    defaultName: cas-proxy
    defaultCasUrl: https://olson.cyverse.org/cas
    defaultCasValidate: validate
    concurrentJobs: 2
    useCaseCharsMin: 60
    initContainerName: input-files-init
    inputFilesContainerName: input-files
    viceProxyContainerName: vice-proxy
    analysisContainerName: analysis
    deploymentTimeoutMs: 180000

amqp:
    amqp_uri: amqp://localhost:15672
    # amqp_uri: amqp://mq:15672 # uncomment for dockerized UI
    exchange_name: amqp

services:
    ontology_lookup_service:
        base: https://www.ebi.ac.uk/ols/api/select
    unified_astronomy_thesaurus:
        base: https://vocabs.ands.org.au/repository/api/lda/aas/the-unified-astronomy-thesaurus/current/concept.json
    user_portal_api:
        base: https://portaldev.cyverse.org/api

grouper:
    allUsers: GrouperAll
    admin: de_grouper

unleash:
    api_url: http://0.0.0.0:4242/api
    client_secret: dsdsd4545
    maintenance_flag: DE-Maintenance

metadata:
    community_attr: cyverse-community
